### PR TITLE
Resize the plane image on the homepage

### PR DESCRIPTION
**Pull request by shauryaaher**
The image doesn't fit on smaller screens.

### CODE REVIEW

**Review by DarrtWorks — APPROVED** [review]
Works fine on Mobile.

**Comment by shauryaaher** [comment]
Nice. Keep up the good work.

**Comment by shauryaaher** [comment]
Incorrect review. It doesn't work on mobile properly.

**Comment by shauryaaher** [comment]
Looks good now, ready to merge.

**Pull request merged**
